In [1]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
np.set_printoptions(edgeitems=10, linewidth=180)
SEED=42

### SVD

$$ \large A_{[\text{m x n}]} = U_{[\text{m x m}]}\Sigma_{[\text{m x n}]}V^T_{[\text{n x n}]}$$
* $A$: Input data matrix
    * $\text{m x n}$ matrix (e.g., $m$ words, $n$ contexts: each element $A_{ij}$ says about the association between a word $i$ and a context $j$)
* $U$: Left singular vectors
    * $\text{m x m}$ matrix (rows are word vectors)
* $\Sigma$: Singular values
    * $\text{m x n}$ matrix (values on the diagonal are the singular values)
* $V^T$: Right singular vectors
    * $\text{n x n}$ matrix (columns are context vectors)

#### SVD Theorem

Let $A \in \mathbb{R}^{\text{m x n}}$ be a rectangular matrix of rank $r \in [0; min(\text{m; n})]$. The SVD of A is a decomposition of the form $$A_{[\text{m x n}]} = U_{[\text{m x m}]}\Sigma_{[\text{m x n}]}V^T_{[\text{n x n}]}$$ 
with an orthogonal matrix $U \in \mathbb{R}^{\text{m x m}}$ with column vectors $u_i, i = 1; ... ;m$ (*left-singular vectors*),  
and an orthogonal matrix $V \in \mathbb{R}^{\text{n x n}}$ with column vectors $v_j, j = 1; ... ;n$ (*right-singular vectors*).  
Moreover, $\Sigma$ is an $\text{m x n}$ matrix with $\Sigma_{ii} = \sigma_i > 0$ and $\Sigma_{ij} = 0; i \neq j$.  

Remarks:
* The diagonal entries $\sigma_i, i = 1; ...; r$, of $\Sigma$ are called the *singular values*.  
* By convention, the singular values are ordered, i.e., $\sigma_1 \geqslant \sigma_2 \geqslant \sigma_r \geqslant 0$.
* The SVD exists for any matrix $A \in \mathbb{R}^{\text{m x n}}$.

$©$ 2021 M. P. Deisenroth, A. A. Faisal, C. S. Ong. Published by Cambridge University Press (2020).

#### SVD Python Implementation

In [2]:
np.random.seed(SEED)
A = np.random.rand(5, 7) # create random data matrix
U, S, V = np.linalg.svd(A)

print(f"A:\n{A}")
print(f"U:\n{U}")
print(f"S:\n{S}")
print(f"V:\n{V}")

A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
U:
[[-0.39184014 -0.66322871  0.27597594  0.57092478 -0.06686672]
 [-0.60689845 -0.13318018 -0.74124561 -0.19370056  0.16423262]
 [-0.33040979  0.09248678  0.4911744  -0.2684105   0.75430702]
 [-0.36567506 -0.10992275  0.34886432 -0.61679441 -0.59334399]
 [-0.48502237  0.72232534  0.10692817  0.42900519 -0.21799156]]
S:
[2.77351184 1.12365801 0.86764052 0.77654903 0.09131995]
V:
[[-0.38610302 -0.33434216 -0.44914883 -0.24154835 -0.40063314 -0.43115174 -0.36422624]
 [ 0.05841249 -0.61602032 -0.13622357 -0.24759711 -0.20648622  0.42367457  0.56134575]
 [-0.38883292  0.0158703   0.02232176  0

#### Truncated SVD

Datasets with large number of features (for example, datasets, where the number of features is more than the number of rows or word-context matrices, which has a lot of uninformative elements (e.g., zeros)) can be reduced/approximated with a lower rank (than original) matrix.  

To do this we need to:
1. Perform SVD operation on the original data
2. Select top k largest singular values
3. Truncate U, S, V accordingly -> Ut, St, Vt
4. Get approximated matrix by doing (one of):
 * $dot(Ut, St)$
 * $dot(A, Vt^T)$

##### Truncated SVD my implementation

In [3]:
n_components=4
U, S, V = np.linalg.svd(A)

In [4]:
Ut = U[:, :n_components]
St = S[:n_components]
Vt = V[:n_components, :]
approx_A = np.dot(Ut * St, Vt)
print(f"Original matrix A:\n{A}")
print(f"Low rank approximation for matrix A (4 out of 5 signular values were used):\n{approx_A}")

Original matrix A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
Low rank approximation for matrix A (4 out of 5 signular values were used):
[[0.37737879 0.95004743 0.7284511  0.60209534 0.15565872 0.15737434 0.05653876]
 [0.85920402 0.60275294 0.71677421 0.01214317 0.97079385 0.82905365 0.21613345]
 [0.14980257 0.19092737 0.34420815 0.48598612 0.43600515 0.27566379 0.62928   ]
 [0.16468294 0.2862271  0.33492434 0.48656702 0.78198223 0.21191762 0.50052614]
 [0.60166891 0.04427634 0.59599487 0.18172858 0.06387823 0.95338386 0.96059567]]


We can see that the matrices are very close

In [5]:
truncated_A_1 = Ut.dot(np.diag(St))
truncated_A_2 = A.dot(Vt.T)

assert np.allclose(truncated_A_1, truncated_A_2)
truncated_A = truncated_A_1

In [6]:
print(f"Original matrix A:\n{A}")
print(f"Truncated matrix A:\n{truncated_A}")

Original matrix A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
Truncated matrix A:
[[-1.08677327 -0.74524225  0.23944791  0.44335109]
 [-1.68324005 -0.14964898 -0.64313472 -0.15041798]
 [-0.91639545  0.10392351  0.42616281 -0.20843391]
 [-1.01420411 -0.12351558  0.30268882 -0.4789711 ]
 [-1.34521527  0.81164666  0.09277521  0.33314356]]


##### Truncated SVD Sklearn's implementation

In [7]:
truncated_svd = TruncatedSVD(n_components=n_components, n_iter=10, random_state=SEED)
truncated_svd.fit(A)

TruncatedSVD(n_components=4, n_iter=10, random_state=42)

In [8]:
truncated_A_sklearn = truncated_svd.transform(A)
print(f"Original matrix A:\n{A}")
print(f"Truncated matrix A:\n{truncated_A_sklearn}")

Original matrix A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
Truncated matrix A:
[[ 1.08677327 -0.74524225 -0.23944791 -0.44335109]
 [ 1.68324005 -0.14964898  0.64313472  0.15041798]
 [ 0.91639545  0.10392351 -0.42616281  0.20843391]
 [ 1.01420411 -0.12351558 -0.30268882  0.4789711 ]
 [ 1.34521527  0.81164666 -0.09277521 -0.33314356]]


##### Truncated SVD scipy's implementation

In [9]:
from scipy.sparse.linalg import svds
U_scipy, S_scipy, V_scipy = svds(A, k=n_components, which='LM')
n = len(S_scipy)
U_scipy[:,:n] = U_scipy[:, n-1::-1]
S_scipy = S_scipy[::-1]
# V_scipy[:n, :] = V_scipy[n-1::-1, :]
truncated_A_scipy = U_scipy.dot(np.diag(S_scipy)) 
print(f"Original matrix A:\n{A}")
print(f"Truncated matrix A:\n{truncated_A_scipy}")

Original matrix A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
Truncated matrix A:
[[-1.08677327  0.74524225 -0.23944791 -0.44335109]
 [-1.68324005  0.14964898  0.64313472  0.15041798]
 [-0.91639545 -0.10392351 -0.42616281  0.20843391]
 [-1.01420411  0.12351558 -0.30268882  0.4789711 ]
 [-1.34521527 -0.81164666 -0.09277521 -0.33314356]]


In [10]:
print(f"Truncated matrix A (my implementation):\n{truncated_A}")
print(f"Truncated matrix A (sklearn implementation):\n{truncated_A_sklearn}")
print(f"Truncated matrix A (scipy implementation):\n{truncated_A_scipy}")

Truncated matrix A (my implementation):
[[-1.08677327 -0.74524225  0.23944791  0.44335109]
 [-1.68324005 -0.14964898 -0.64313472 -0.15041798]
 [-0.91639545  0.10392351  0.42616281 -0.20843391]
 [-1.01420411 -0.12351558  0.30268882 -0.4789711 ]
 [-1.34521527  0.81164666  0.09277521  0.33314356]]
Truncated matrix A (sklearn implementation):
[[ 1.08677327 -0.74524225 -0.23944791 -0.44335109]
 [ 1.68324005 -0.14964898  0.64313472  0.15041798]
 [ 0.91639545  0.10392351 -0.42616281  0.20843391]
 [ 1.01420411 -0.12351558 -0.30268882  0.4789711 ]
 [ 1.34521527  0.81164666 -0.09277521 -0.33314356]]
Truncated matrix A (scipy implementation):
[[-1.08677327  0.74524225 -0.23944791 -0.44335109]
 [-1.68324005  0.14964898  0.64313472  0.15041798]
 [-0.91639545 -0.10392351 -0.42616281  0.20843391]
 [-1.01420411  0.12351558 -0.30268882  0.4789711 ]
 [-1.34521527 -0.81164666 -0.09277521 -0.33314356]]


We can see that the values match between several implementations, except for the sign on some values. We can expect there to be some instability when it comes to the sign given the nature of the calculations involved and the differences in the underlying libraries and methods used. This instability of sign should not be a problem in practice as long as the transform is trained for reuse.

### TODO
* Investigate how SVD is done analytically and computationally 
* Investigate difference in signs
* Investigate geometric interpretation of SVD
* Write about economy SVD
* Write about the form of $\Sigma$ matrix when $m>n$, $m<n$ and $m==n$
* Briefly discuss SVD terminology and conventions